/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Consultas.vcempleado;
import DATOS.Dempleados;
import DATOS.conexion;
import DATOS.datos;
import DATOS.fotoclass;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.ImageIcon;
/**
 *
 * @author Mxcatv
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public vcempleado objemp=new vcempleado();
    public fotoclass objfoto=new fotoclass();
    public Dempleados dtsemp=new Dempleados();
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);
        cbusers.setModel(objemp.usuariosemp());
        dtsemp.setUsuario(String.valueOf(cbusers.getSelectedItem()));
        if(objfoto.fotoexistelo(dtsemp)){
            cargarfoto();
        }
        else{
            lblfotouser.setIcon(new ImageIcon(getClass().getResource("/Imagenes/fotoblanco.jpg")));
        }
    }
    public int contar=1;
    conexion objcon=new conexion();
    datos objdatos=new datos();
    public void cargarfoto(){
        Image tmg=objfoto.recuperarfotoslo(dtsemp);
        ImageIcon ico=new ImageIcon(tmg);
        Image img=ico.getImage();
        Image newimg=img.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon newicon=new ImageIcon(newimg);
        lblfotouser.setIcon(newicon);
    }
    public void verificardatos(){
        
        if(objdatos.validauser(String.valueOf(cbusers.getSelectedItem()), txtpass.getText())){
            JOptionPane.showMessageDialog(null,"usuario y contrase correctos");
            this.dispose();
            String usuario=String.valueOf(cbusers.getSelectedItem());
            Principal objfrm1=new Principal(usuario);
            objfrm1.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"usuario y contrase incorrectos");
            contar++;
            if(contar>3){
                JOptionPane.showMessageDialog(null, "Se Acabaron tus intentos ADIOS");
                txtpass.setText(null);
                cbusers.requestFocus();
                System.exit(0);
            }
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnentrar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        lblfotouser = new javax.swing.JLabel();
        cbusers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnentrar.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnentrar.setText("ENTRAR");
        btnentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        btnsalir.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 11)); // NOI18N
        btnsalir.setText("CANCELAR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel1.setText("USUARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jLabel2.setText("CONTRASEÑA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 150, 150, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfotouser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblfotouser, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        cbusers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbusersItemStateChanged(evt);
            }
        });
        getContentPane().add(cbusers, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 120, 150, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel3.setText("Acceso al Sistema");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/depositphotos_9717629-stock-illustration-pattern-of-bananas.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentrarActionPerformed
        // TODO add your handling code here:
        if(objdatos.validauser(String.valueOf(cbusers.getSelectedItem()), txtpass.getText())){
            JOptionPane.showMessageDialog(null,"usuario y contrase correctos");
            this.dispose();
            String usuario=String.valueOf(cbusers.getSelectedItem());
            Principal objfrm1=new Principal(usuario);
            objfrm1.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"usuario y contrase incorrectos");
            contar++;
            if(contar>3){
                JOptionPane.showMessageDialog(null, "Se Acabaron tus intentos ADIOS");
                txtpass.setText(null);
                cbusers.requestFocus();
                System.exit(0);
            }
        }
    }//GEN-LAST:event_btnentrarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        int Opcion = JOptionPane.showConfirmDialog(null, "Esta seguro de salir", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (Opcion==JOptionPane.YES_OPTION){
            System.exit(0);
        }
        else{
            txtpass.requestFocus();
        }
    }//GEN-LAST:event_btnsalirActionPerformed

    private void cbusersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbusersItemStateChanged
        // TODO add your handling code here:
        dtsemp.setUsuario(String.valueOf(cbusers.getSelectedItem()));
        
        if(objfoto.fotoexistelo(dtsemp)){
            cargarfoto();
        }
        else{
            lblfotouser.setIcon(new ImageIcon(getClass().getResource("/Imagenes/fotoblanco.jpg")));
        }
        
    }//GEN-LAST:event_cbusersItemStateChanged

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
        verificardatos();
    }//GEN-LAST:event_txtpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnentrar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cbusers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblfotouser;
    private javax.swing.JPasswordField txtpass;
    // End of variables declaration//GEN-END:variables
}
